'BmLayMAL' ' ' ;  x Biomass of MALS in segment                             (gDM/m3)
'BrochP' ' ' ;  x gross production as per Broch                          (gC/dm2/h)
'ExudMALC' ' ' ;  x exudation MALC                                         (gC/m2/d)
'FrBmMALS' ' ' ;  x Fraction of bottom layer MALS in this seg              (-)
'GrosMALC' ' ' ;  x gross photosynthesis MALC                              (gC/m2/d)
'LimDenS' ' ' ;  x biomass density limitation MALS                        (-)
'LimMALC' ' ' ;  x carbon storage limitation MALS                       (-)
'LimMALN' ' ' ;  x nitrogen storage limitation MALS                       (-)
'LimMALP' ' ' ;  x phosphrous storage limitation MALS                       (-)
'LimN' ' ' ;  x ambient nitrogen limitation for storage                (-)
'LimNutS' ' ' ;  x net nutrient storage limitation MALS                   (-)
'LimP' ' ' ;  x ambient phosphorous limitation for storage             (-)
'LimPhoS' ' ' ;  x photoperiod limitation MALS                            (-)
'LimTemS' ' ' ;  x temperature limitation MALS                            (-)
'LimVel' ' ' ;  x velocity limitation                                    (-)
'LocDecS' ' ' ;  x local decay of MALS                                    (DM/m2/d)
'LocGroC' ' ' ;  x local utilization of MALC by MALS                      (gC/m2/d)
'LocGroN' ' ' ;  x local utilization of MALN by MALS                      (gN/m2/d)
'LocGroP' ' ' ;  x local utilization of MALP by MALS                      (gP/m2/d)
'LocGroPS' ' ' ;  x local gross production of MALS                         (DM/m2/d)
'LocNetPS' ' ' ;  x local net production of MALS                           (DM/m2/d)
'LocUpC' ' ' ;  x Local C storage uptake flux in this segment            (gC/m2/d)
'LocUpN' ' ' ;  x Local N storage uptake flux in this segment            (gN/m2/d)
'LocUpP' ' ' ;  x Local P storage uptake flux in this segment            (gP/m2/d)
'MALSCDM' ' ' ;  x ratio C:DM in whole frond                              (gC/gDM)
'MALSNDM' ' ' ;  x ratio N:DM in whole frond                              (gN/gDM)
'MALSPDM' ' ' ;  x ratio P:DM in whole frond                              (gP/gDM)
'MALSNC' ' ' ;  x ratio N:C in whole frond                               (gN/gC)
'MALSPC' ' ' ;  x ratio P:C in whole frond                               (gP/gC)
'muMALS' ' ' ;  x unit growth rate MALS                                  (1/d)
'RespMALC' ' ' ;  x respiration MALC                                       (gC/m2/d)
'WDry' ' ' ;  x dry weight of culture in segment                       (g/m2)
'Wwet' ' ' ;  x dry weight of culture in segment                       (g/m2)
'WdryTot' ' ' ;  x dry weight of culture in segment                       (g)
'WwetTot' ' ' ;  x wet weight of culture in segment                       (g)
'MALCDMS' ' ' ;  x macroalgae C storage in column w.r.t structural        (gC/gDM)
'MALNDMS' ' ' ;  x macroalgae N storage in column w.r.t structural        (gN/gDM)
'MALPDMS' ' ' ;  x macroalgae P storage in column w.r.t structural        (gP/gDM)
'FootDepth' ' ' ;  x location of frond attachment in the water column < MSL (m)
'FrondArea' ' ' ;  x area of each individual frond in segment               (m2/m2/frond)
'LocAreaMAL' ' ' ;  x area of all fronds per m2 of column                    (m2/m2)
'TotAreaMAL' ' ' ;  x area of frond in this column                           (m2)
'LengthMAL' ' ' ;  x length of frond in this column                         (m)
'TipDepth' ' ' ;  x depth of tip of frond in this column                   (m)
'SpecArea' ' ' ;  x area of a single frond                                 (dm2) 
'FrNH4MALN' ' ' ; x fraction ammonium uptake by MALN                       (-)   
'mrtMALS' ' ' ;
'NFrond' ' ' ; number of frond per segment
'M_Vind'       'M_Nind'
'M_Eind'       'M_Nind'
'M_Rind'       'M_Nind'
'M_TotBiom'    ' '
'M_Biomass'    'surf'
'M_TotWW'      ' '
'M_WW'         'surf'
'M_TotAFDW'    ' '
'M_AFDW'       'surf'
'M_GrossGr'    'surf'
'M_NetGr'      'surf'
'M_Nind'       'surf'
'M_Length'     'M_Nind'
'M_GSI'        'M_Nind'
'M_Escaled'    'M_Nind'
'M_Nbal'       ' '
'M_Pbal'       ' '
'M_Cbal'       ' '
