; DEB constants blue mussel
CONSTANTS 'M_Lref'            DATA        1.50000e+000 ; based on avg length VZM area A ; ref length of DEB
CONSTANTS 'M_Dummy'           DATA        1.00000e+000 ; dummy constant for DEB Mussel
CONSTANTS 'M_Vb'              DATA        0.100000e-05 ; volume at birth individual DEB Mussel
CONSTANTS 'M_Vp'              DATA        0.600000E-01 ; volume at start of repro stage ind DEB Mussel
CONSTANTS 'M_shape'           DATA        0.437000     ; shape coefficient of DEB Mussel
CONSTANTS 'M_Em'              DATA        1136.00      ; maximum storage density of DEB Mussel
CONSTANTS 'M_Eg'              DATA        1900.00      ; volume-spec costs for growth of DEB Mussel
CONSTANTS 'M_Pm'              DATA        30.7000      ; respiration rate constant of DEB Mussel
CONSTANTS 'M_JXm'             DATA        196.800      ; max ingestion rate of DEB Mussel
CONSTANTS 'M_kappaI'          DATA        1.00000      ; ingestion efficiency of DEB Mussel
CONSTANTS 'M_kappaA'          DATA        0.800000     ; assimilation efficiency of DEB Mussel
CONSTANTS 'M_kappa'           DATA        0.880000     ; fraction of energy spent on growth DEB Mussel
CONSTANTS 'M_kappaR'          DATA        0.120000     ; fraction of energy spent on gonads DEB Mussel
CONSTANTS 'M_Ta'              DATA        9500.00      ; arrhenius temperature of DEB Mussel
CONSTANTS 'M_Tah'             DATA        27079.0      ; arr temp for upper boundary DEB Mussel
CONSTANTS 'M_Tal'             DATA        57048.0      ; arr temp for lower boundary DEB Mussel
CONSTANTS 'M_Th'              DATA        305.000      ; upper boundary of tolerance range of DEB Mussel
CONSTANTS 'M_Tl'              DATA        275.000      ; lower boundary of tolerance range of DEB Mussel
CONSTANTS 'M_GSIupr'          DATA        0.012000     ; minimum GSI for spawning of DEB Mussel
CONSTANTS 'M_GSIlwr'          DATA        0.100000     ; minimum GSI while spawning of DEB Mussel
CONSTANTS 'M_DoSpawn'         DATA        0.00000      ; indication of spawning of DEB Mussel
CONSTANTS 'M_rSpawn'          DATA        0.020000     ; spawning rate of DEB Mussel
CONSTANTS 'M_MinSTmp'         DATA        12.0000      ; minimum temperature for spawning of DEB Mussel
CONSTANTS 'M_Xk'              DATA        0.100000     ; halfrate const for food of DEB Mussel
CONSTANTS 'M_Yk'              DATA        100.000      ; halfrate const for TIM of DEB Mussel
CONSTANTS 'M_rMor'            DATA        0.000     ; reference mortality rate of DEB Mussel
CONSTANTS 'M_rMor'            DATA        0.000       ; reference mortality rate of DEB Mussel

CONSTANTS 'M_cMor'            DATA        0.00000      ; length coefficient harvesting rate DEB Mussel
CONSTANTS 'M_rHrv'            DATA        0.00000      ; reference rate of harvesting of DEB Mussel
CONSTANTS 'M_cHrv'            DATA        0.00000      ; length coefficient harvesting rate DEB Mussel
CONSTANTS 'M_cEC'             DATA        0.174000E-04 ; energy to carbon conversion of DEB Mussel
CONSTANTS 'M_cVC'             DATA        0.480000E-01 ; volume to carbon conversion of DEB Mussel
CONSTANTS 'M_cAFWC'           DATA        0.400000     ; AFD weight to carbon conv of DEB Mussel
CONSTANTS 'M_cWWC'            DATA        0.224000E-01 ; wetweight to carbon conv of DEB Mussel
CONSTANTS 'M_TC'              DATA        1.00000e+000 ; C:C ratio of DEB Mussel
CONSTANTS 'M_TN'              DATA        0.181800     ; N:C ratio of DEB Mussel
CONSTANTS 'M_TP'              DATA        0.263000E-01 ; P:C ratio of DEB Mussel
CONSTANTS 'M_TSi'             DATA        0.00000      ; Si:C ratio of DEB Mussel
CONSTANTS 'M_FrDetS1'         DATA        1.00000e+000 ; fraction of DEB Mussel detritus into sediment
CONSTANTS 'M_SWBen'           DATA        1.00000e+000 ; SWBen specifies the location of the grazers, pelagi
CONSTANTS 'M_SFSusp'          DATA        1.00000e+000 ; DEB Mussel pref suspension over deposit feeding
CONSTANTS 'M_PrDet'           DATA        0.00000      ; DEB Mussel preference for DetC or POC1
CONSTANTS 'M_PrDetS1'         DATA        0.00000      ; DEB Mussel preference for DetCS1
CONSTANTS 'M_FFDet'           DATA        0.500000     ; Faecal fraction of DetC for DEB Mussel
CONSTANTS 'M_FFDetS1'         DATA        0.500000     ; Faecal fraction of DetCS1 for DEB Mussel
;CONSTANTS 'M_ALGFFGRN'        DATA        0.0          ; Egested fraction of green algae consumed by mussel
;CONSTANTS 'M_ALGFFDIAT'       DATA        0.0          ; Egested fraction of diatoms consumed by mussels
;CONSTANTS 'M_ALGFFALG01'      DATA        0.0          ; Egested fraction of ALG01 consumed by mussels
;CONSTANTS 'M_ALGFFALG02'      DATA        0.0          ; Egested fraction of ALG02 consumed by mussels
;CONSTANTS 'M_ALGFFALG03'      DATA        0.0          ; Egested fraction of ALG03 consumed by mussels
;CONSTANTS 'M_ALGFFALG04'      DATA        0.0          ; Egested fraction of ALG04 consumed by mussels
;CONSTANTS 'M_ALGFFALG05'      DATA        0.0          ; Egested fraction of ALG05 consumed by mussels
;CONSTANTS 'M_ALGFFALG06'      DATA        0.0          ; Egested fraction of ALG06 consumed by mussels
;CONSTANTS 'M_ALGFFALG07'      DATA        0.0          ; Egested fraction of ALG07 consumed by mussels
;CONSTANTS 'M_ALGFFALG08'      DATA        0.0          ; Egested fraction of ALG08 consumed by mussels
;CONSTANTS 'M_ALGFFALG09'      DATA        0.0          ; Egested fraction of ALG09 consumed by mussels
;CONSTANTS 'M_ALGFFALG10'      DATA        0.0          ; Egested fraction of ALG10 consumed by mussels
;CONSTANTS 'M_ALGFFALG11'      DATA        0.0          ; Egested fraction of ALG11 consumed by mussels
;CONSTANTS 'M_ALGFFALG12'      DATA        0.0          ; Egested fraction of ALG12 consumed by mussels
;CONSTANTS 'M_ALGFFALG13'      DATA        0.0          ; Egested fraction of ALG13 consumed by mussels
;CONSTANTS 'M_ALGFFALG14'      DATA        0.0          ; Egested fraction of ALG14 consumed by mussels
;CONSTANTS 'M_ALGFFALG15'      DATA        0.0          ; Egested fraction of ALG15 consumed by mussels
;CONSTANTS 'M_ALGFFALG16'      DATA        0.0          ; Egested fraction of ALG16 consumed by mussels
;CONSTANTS 'M_ALGFFALG17'      DATA        0.0          ; Egested fraction of ALG17 consumed by mussels
;CONSTANTS 'M_ALGFFALG18'      DATA        0.0          ; Egested fraction of ALG18 consumed by mussels
;CONSTANTS 'M_ALGFFALG19'      DATA        0.0          ; Egested fraction of ALG19 consumed by mussels
;CONSTANTS 'M_ALGFFALG20'      DATA        0.0          ; Egested fraction of ALG20 consumed by mussels
;CONSTANTS 'M_ALGFFALG21'      DATA        0.0          ; Egested fraction of ALG21 consumed by mussels
;CONSTANTS 'M_ALGFFALG22'      DATA        0.0          ; Egested fraction of ALG22 consumed by mussels
;CONSTANTS 'M_ALGFFALG23'      DATA        0.0          ; Egested fraction of ALG23 consumed by mussels
;CONSTANTS 'M_ALGFFALG24'      DATA        0.0          ; Egested fraction of ALG24 consumed by mussels
;CONSTANTS 'M_ALGFFALG25'      DATA        0.0          ; Egested fraction of ALG25 consumed by mussels
;CONSTANTS 'M_ALGFFALG26'      DATA        0.0          ; Egested fraction of ALG26 consumed by mussels
;CONSTANTS 'M_ALGFFALG27'      DATA        0.0          ; Egested fraction of ALG27 consumed by mussels
;CONSTANTS 'M_ALGFFALG28'      DATA        0.0          ; Egested fraction of ALG28 consumed by mussels
;CONSTANTS 'M_ALGFFALG29'      DATA        0.0          ; Egested fraction of ALG29 consumed by mussels
;CONSTANTS 'M_ALGFFALG30'      DATA        0.0          ; Egested fraction of ALG30 consumed by mussels

CONSTANTS 'M_SwBen' DATA 2 ; suspended
CONSTANTS 'M_SwV1'  DATA 0 ; isomorph
CONSTANTS 'ACTIVE_DEBGRZ_M' DATA 1.0

