 ; dedicated input for MALG
 CONSTANTS
 'ACTIVE_FLMALS'
 'ACTIVE_DAYLP'
 'ACTIVE_MALDIS'
 'ACTIVE_FLMALN'
 'ACTIVE_FLMALC'
 'ACTIVE_HRVMAL'
 DATA
 1.0 ;
 1.0 ;
 1.0 ;
 1.0 ;
 1.0 ;
 1.0 ;
 
 
 CONSTANTS 'Latitude'  DATA 52
 CONSTANTS 'ExtVl'     DATA 0.18
 CONSTANTS 'MALS0'     DATA 0.06
 CONSTANTS 'mrtMAL'    DATA 0.18 
 CONSTANTS 'SWRear'    DATA 10.0
 CONSTANTS 'SWRearCO2' DATA 11.0
 CONSTANTS 'LmaxMAL'   DATA 8
 CONSTANTS 'LinDenMAL' DATA 120
 CONSTANTS 'LinDenCor' DATA 0.0
 CONSTANTS 'FStretch'  DATA 1.0
 CONSTANTS 'SeedMass'  DATA 0.5
 ; will become = 0.0 if no footdepth, grows at surface
 CONSTANTS 'SWGroDir'     DATA -1.0 ; grows downward
 CONSTANTS 'nothreads' DATA 4
 CONSTANTS 'Velocity'  DATA 0.15
