; number of active and inactive substances
23             12
        ; active substances
1            'Continuity' ;Continuity
2            'OXY' ;Dissolved Oxygen
3            'Salinity' ;Salinity
4            'NH4' ;Ammonium (NH4)
5            'NO3' ;Nitrate (NO3)
6            'PO4' ;Ortho-Phosphate (PO4)
7            'Si' ;dissolved Silica (Si)
8            'Opal' ;Opal-Si
9            'POC1' ;POC1 (fast decomposing fraction)
10            'PON1' ;PON1 (fast decomposing fraction)
11            'POP1' ;POP1 (fast decomposing fraction)
12            'DINOFLAG_E' ;Marine DINOFLAG energy type
13            'DINOFLAG_N' ;Marine DINOFLAG nitrogen type
14            'DINOFLAG_P' ;Marine DINOFLAG phosphorus typ
15            'MDIATOMS_E' ;Marine DIATOMS energy type
16            'MDIATOMS_N' ;Marine DIATOMS nitrogen type
17            'MDIATOMS_P' ;Marine DIATOMS phosphorus type
18            'MFLAGELA_E' ;Marine FLAGELAT energy type
19            'MFLAGELA_N' ;Marine FLAGELAT nitrogen type
20            'MFLAGELA_P' ;Marine FLAGELAT phosphorus typ
21            'PHAEOCYS_E' ;Phaeocystis energy type
22            'PHAEOCYS_N' ;Phaeocystis nitrogen type
23            'PHAEOCYS_P' ;Phaeocystis phosphorus type
        ; passive substances
24            'DetCS1' ;DetC in layer S1
25            'DetNS1' ;DetN in layer S1
26            'DetPS1' ;DetP in layer S1
27            'DetSiS1' ;DetSi in layer S1
28            'MALS'
29            'MALN'
30            'MALP'
31            'MALC'
32            'Mussel_V'
33            'Mussel_E'
34            'Mussel_R'
35            'Mussel_N'