MASS/M2
 1 ; initial conditions follow
 2 ; all values with default
 21*1.0 ; scale factors

1
7
0.05
0.1
0.01
30
200
1
1
0.2
0.2
0.01
0.01
1
0
0
0
0
0
0
0
3  ; number of overridings
 9836; first overriding
1
7
0.05
0.1
0.01
30
200
1
1
0.2
0.2
0.01
0.01
1
0
0
0
	  18.0 ;'MALS' area = 0.3 m2, with 60 g/m2 = 18 g in a m2
	  0.18 ;'MALN' gN/gDM = 0.01, so 18 * 0.01 = 0.18, equals minimal, but will add a tiny bit, because the frond begins by dying
	  0.018 ;'MALP'
	  10.8 ;'MALC' gC/gDM = 0.6, so 18 * 0.35 = 6.3 gC/m2


9845; first overriding
1
7
0.05
0.1
0.01
30
200
1
1
0.2
0.2
0.01
0.01
1
0
0
0
	  18.0 ;'MALS' area = 0.3 m2, with 60 g/m2 = 18 g in a m2
	  0.18 ;'MALN' gN/gDM = 0.01, so 18 * 0.01 = 0.18, equals minimal, but will add a tiny bit, because the frond begins by dying
	  0.018 ;'MALP'
	  10.8 ;'MALC' gC/gDM = 0.6, so 18 * 0.35 = 6.3 gC/m2
	  
9866; first overriding
1
7
0.05
0.1
0.01
30
200
1
1
0.2
0.2
0.01
0.01
1
0
0
0
	  18.0 ;'MALS' area = 0.3 m2, with 60 g/m2 = 18 g in a m2
	  0.18 ;'MALN' gN/gDM = 0.01, so 18 * 0.01 = 0.18, equals minimal, but will add a tiny bit, because the frond begins by dying
	  0.018 ;'MALP'
	  10.8 ;'MALC' gC/gDM = 0.6, so 18 * 0.35 = 6.3 gC/m2
