2 ; perform default output and extra parameters listed below
57 ; number of extra variables
  'SURF' ' '
  'LocalDepth' ' '
  'TotalDepth' ' '
  'Depth' ' '
  'Temp' ' '
  'RadSurf' ' '
  'Itip' ' '
  'Itipu' ' '
  'BrochP' ' '                      ;x gross production as per Broch                          (gC/dm2/h)
  'pH' ' '
  'DisCO2' ' '
  'pCO2water' ' '
  'DisHCO3' ' '
  'CO2' ' '
  'beta' ' '
  'daylend' ' '                     ;x daylength default definition                           (-)                 
  'daylenp' ' '                     ;x daylength of previous day                              (-)                 
  'daylenm' ' '                     ;x maximum daylength at this latitude                     (-)   
  'MALNDM' ' '                      ;x macroalgae N storage in segment                        (gN/gDM)            
  'MALPDM' ' '                      ;x macroalgae P storage in segment                        (gP/gDM)            
  'MALCDM' ' '                      ;x macroalgae C storage in segment                        (gC/gDM)            
  'MALSNC' ' '                      ;x ratio N:C in whole frond                               (gN/gC)             
  'MALSPC' ' '                      ;x ratio P:C in whole frond                               (gP/gC)             
  'MALSCD' ' '                      ;x ratio C:DM in whole frond                              (gC/gDM)             
  'MALSND' ' '                      ;x ratio N:DM in whole frond                              (gN/gDM)
  'MALSPD' ' '                      ;x ratio P:DM in whole frond                              (gP/gDM) 
  'LimDenS' ' '                     ;x biomass limitation MALS                                (-)                 
  'LimPhoS' ' '                     ;x photoperiod limitation MALS                            (-)                 
  'LimTemS' ' '                     ;x temperature limitation MALS                            (-)                 
  'LimN' ' '                        ;x ambient nitrogen limitation for storage                (-)
  'LimP' ' '                        ;x ambient phosphorous limitation for storage             (-)
  'LimNutS' ' '                     ;x nutrient storage limitation MALS                       (-)                 
  'LimMALN' ' '                     ;x nitrogen storage limitation MALS                       (-)
  'LimMALP' ' '                     ;x phosphorous storage limitation MALS                    (-)
  'LimMALC' ' '                     ;x carbon storage limitation MALS                         (-)
  'muMALS' ' '
  'LocGroPS' ' '                    ;x local gross production of MALS                         (DM/m2/d)           
  'LocNetPS' ' '                    ;x local net production of MALS                           (DM/m2/d)           
  'LocDecS' ' '                     ;x local decay of MALS                                    (DM/m2/d)           
  'LocGroN' ' '                     ;x local growth of MALN                                   (gN/m3/d)           
  'LocGroP' ' '                     ;x local growth of MALP                                   (gP/m3/d)           
  'LocGroC' ' '                     ;x local growth of MALC                                   (gC/m3/d)     
  'GrosMALC' ' '                    ;x gross photosynthesis MALC                              (gC/m2/d) 
  'RespMALC' ' '                    ;x respiration MALC                                       (gC/m2/d)             
  'ExudMALC' ' '                    ;x exudation MALC                                         (gC/m2/d) 
  'FrBmMALS' ' '                    ;x Fraction of bottom layer MALS in this seg              (DM/m2)             
  'BmLayMAL' ' '                    ;x   Biomass of MALS in segment                            (gDM/m2)           
  'LengthMAL' ' '                    ;x length of frond in this column                         (m)                 
  'AreaMAL' ' '                     ;x area of frond in this column                           (m2)                
  'TipDepth' ' '                    ;x depth of tip of frond in this column                   (m)                 
  'LimVel' ' '                      ;x velocity limitation                                    (-)                 
  'LocUpN' ' '                      ;x Local N storage uptake flux                            (gN/m3/d)           
  'LocUpP' ' '                      ;x Local P storage uptake flux                            (gP/m3/d)   
  'LocUpC' ' '                      ;x Local C uptake flux                                    (gC/m3/d)   
  'Wdry' ' '  
  'Wwet' ' '
  'MBotSeg' ' '                     ;x bottom segment for this segment                        (-)     
