'1 (Left-right 1)' '1 (Left-right 1)' '1/1 (Left-right 1)'
'2 (Left-right 2)' '2 (Left-right 2)' '2/1 (Left-right 2)'
'3 (Left-right 1)' '3 (Left-right 1)' '1/1 (Left-right 1)'
'4 (Left-right 2)' '4 (Left-right 2)' '2/1 (Left-right 2)'
'5 (Left-right 1)' '5 (Left-right 1)' '1/1 (Left-right 1)'
'6 (Left-right 2)' '6 (Left-right 2)' '2/1 (Left-right 2)'
'7 (Left-right 1)' '7 (Left-right 1)' '1/2 (Left-right 1)'
'8 (Left-right 2)' '8 (Left-right 2)' '2/2 (Left-right 2)'
'9 (Left-right 1)' '9 (Left-right 1)' '1/2 (Left-right 1)'
'10 (Left-right 2)' '10 (Left-right 2)' '2/2 (Left-right 2)'
'11 (Left-right 1)' '11 (Left-right 1)' '1/2 (Left-right 1)'
'12 (Left-right 2)' '12 (Left-right 2)' '2/2 (Left-right 2)'
'13 (Left-right 1)' '13 (Left-right 1)' '1/3 (Left-right 1)'
'14 (Left-right 2)' '14 (Left-right 2)' '2/3 (Left-right 2)'
'15 (Left-right 1)' '15 (Left-right 1)' '1/3 (Left-right 1)'
'16 (Left-right 2)' '16 (Left-right 2)' '2/3 (Left-right 2)'
'17 (Left-right 1)' '17 (Left-right 1)' '1/3 (Left-right 1)'
'18 (Left-right 2)' '18 (Left-right 2)' '2/3 (Left-right 2)'
'19 (Left-right 1)' '19 (Left-right 1)' '1/4 (Left-right 1)'
'20 (Left-right 2)' '20 (Left-right 2)' '2/4 (Left-right 2)'
'21 (Left-right 1)' '21 (Left-right 1)' '1/4 (Left-right 1)'
'22 (Left-right 2)' '22 (Left-right 2)' '2/4 (Left-right 2)'
'23 (Left-right 1)' '23 (Left-right 1)' '1/4 (Left-right 1)'
'24 (Left-right 2)' '24 (Left-right 2)' '2/4 (Left-right 2)'
'25 (Left-right 1)' '25 (Left-right 1)' '1/5 (Left-right 1)'
'26 (Left-right 2)' '26 (Left-right 2)' '2/5 (Left-right 2)'
'27 (Left-right 1)' '27 (Left-right 1)' '1/5 (Left-right 1)'
'28 (Left-right 2)' '28 (Left-right 2)' '2/5 (Left-right 2)'
'29 (Left-right 1)' '29 (Left-right 1)' '1/5 (Left-right 1)'
'30 (Left-right 2)' '30 (Left-right 2)' '2/5 (Left-right 2)'
'31 (Left-right 1)' '31 (Left-right 1)' '1/6 (Left-right 1)'
'32 (Left-right 2)' '32 (Left-right 2)' '2/6 (Left-right 2)'
'33 (Left-right 1)' '33 (Left-right 1)' '1/6 (Left-right 1)'
'34 (Left-right 2)' '34 (Left-right 2)' '2/6 (Left-right 2)'
'35 (Left-right 1)' '35 (Left-right 1)' '1/6 (Left-right 1)'
'36 (Left-right 2)' '36 (Left-right 2)' '2/6 (Left-right 2)'
'37 (Left-right 1)' '37 (Left-right 1)' '1/7 (Left-right 1)'
'38 (Left-right 2)' '38 (Left-right 2)' '2/7 (Left-right 2)'
'39 (Left-right 1)' '39 (Left-right 1)' '1/7 (Left-right 1)'
'40 (Left-right 2)' '40 (Left-right 2)' '2/7 (Left-right 2)'
'41 (Left-right 1)' '41 (Left-right 1)' '1/7 (Left-right 1)'
'42 (Left-right 2)' '42 (Left-right 2)' '2/7 (Left-right 2)'
'43 (Left-right 1)' '43 (Left-right 1)' '1/8 (Left-right 1)'
'44 (Left-right 2)' '44 (Left-right 2)' '2/8 (Left-right 2)'
'45 (Left-right 1)' '45 (Left-right 1)' '1/8 (Left-right 1)'
'46 (Left-right 2)' '46 (Left-right 2)' '2/8 (Left-right 2)'
'47 (Left-right 1)' '47 (Left-right 1)' '1/8 (Left-right 1)'
'48 (Left-right 2)' '48 (Left-right 2)' '2/8 (Left-right 2)'
'49 (Left-right 1)' '49 (Left-right 1)' '1/9 (Left-right 1)'
'50 (Left-right 2)' '50 (Left-right 2)' '2/9 (Left-right 2)'
'51 (Left-right 1)' '51 (Left-right 1)' '1/9 (Left-right 1)'
'52 (Left-right 2)' '52 (Left-right 2)' '2/9 (Left-right 2)'
'53 (Left-right 1)' '53 (Left-right 1)' '1/9 (Left-right 1)'
'54 (Left-right 2)' '54 (Left-right 2)' '2/9 (Left-right 2)'
'55 (Left-right 1)' '55 (Left-right 1)' '1/10 (Left-right 1)'
'56 (Left-right 2)' '56 (Left-right 2)' '2/10 (Left-right 2)'
'57 (Left-right 1)' '57 (Left-right 1)' '1/10 (Left-right 1)'
'58 (Left-right 2)' '58 (Left-right 2)' '2/10 (Left-right 2)'
'59 (Left-right 1)' '59 (Left-right 1)' '1/10 (Left-right 1)'
'60 (Left-right 2)' '60 (Left-right 2)' '2/10 (Left-right 2)'
;
; Thatcher-Harleman timelags
;
   2 ; use defaults
   000000000000000
   60    ; Number of overridings
          1     00000000000000   ; Left-right 1
          7     00000000000000   ; Left-right 1
         13     00000000000000   ; Left-right 1
         19     00000000000000   ; Left-right 1
         25     00000000000000   ; Left-right 1
         31     00000000000000   ; Left-right 1
         37     00000000000000   ; Left-right 1
         43     00000000000000   ; Left-right 1
         49     00000000000000   ; Left-right 1
         55     00000000000000   ; Left-right 1
          3     00000000000000   ; Left-right 1
          9     00000000000000   ; Left-right 1
         15     00000000000000   ; Left-right 1
         21     00000000000000   ; Left-right 1
         27     00000000000000   ; Left-right 1
         33     00000000000000   ; Left-right 1
         39     00000000000000   ; Left-right 1
         45     00000000000000   ; Left-right 1
         51     00000000000000   ; Left-right 1
         57     00000000000000   ; Left-right 1
          5     00000000000000   ; Left-right 1
         11     00000000000000   ; Left-right 1
         17     00000000000000   ; Left-right 1
         23     00000000000000   ; Left-right 1
         29     00000000000000   ; Left-right 1
         35     00000000000000   ; Left-right 1
         41     00000000000000   ; Left-right 1
         47     00000000000000   ; Left-right 1
         53     00000000000000   ; Left-right 1
         59     00000000000000   ; Left-right 1
          2     00000000000000   ; Left-right 2
          8     00000000000000   ; Left-right 2
         14     00000000000000   ; Left-right 2
         20     00000000000000   ; Left-right 2
         26     00000000000000   ; Left-right 2
         32     00000000000000   ; Left-right 2
         38     00000000000000   ; Left-right 2
         44     00000000000000   ; Left-right 2
         50     00000000000000   ; Left-right 2
         56     00000000000000   ; Left-right 2
          4     00000000000000   ; Left-right 2
         10     00000000000000   ; Left-right 2
         16     00000000000000   ; Left-right 2
         22     00000000000000   ; Left-right 2
         28     00000000000000   ; Left-right 2
         34     00000000000000   ; Left-right 2
         40     00000000000000   ; Left-right 2
         46     00000000000000   ; Left-right 2
         52     00000000000000   ; Left-right 2
         58     00000000000000   ; Left-right 2
          6     00000000000000   ; Left-right 2
         12     00000000000000   ; Left-right 2
         18     00000000000000   ; Left-right 2
         24     00000000000000   ; Left-right 2
         30     00000000000000   ; Left-right 2
         36     00000000000000   ; Left-right 2
         42     00000000000000   ; Left-right 2
         48     00000000000000   ; Left-right 2
         54     00000000000000   ; Left-right 2
         60     00000000000000   ; Left-right 2