; number of active and inactive substances
14             7
        ; active substances
1        'Continuity' ;Continuity
2        'OXY'
3        'NH4' ;Ammonium (NH4)
4        'NO3' ;Nitrate (NO3)
5        'PO4' ;Ortho-Phosphate (PO4)
6        'TIC'
7        'ALKA'
8        'POC1'
9        'POC2'
10       'PON1'
11       'PON2'
12       'POP1'
13       'POP2'
14       'DOC' ;
        ; passive substances
15       'DectCS1'
16       'DetNS1'
17       'DetPS1'
18       'MALS'
19       'MALN'
20       'MALP'
21       'MALC'