MASS/M2
 1 ; initial conditions follow
 2 ; all values with default
 35*1.0 ; scale factors
1 ;'Continuity'
7 ; 'OXY'
34 ; 'Salinity'
0.01  ; 'NH4'
0.01 ; 'NO3'
0.001; 'PO4'
0.1; 'Si'
0.1; 'Opal'
1 ;'POC1'
0.2; 'PON1'
0.01; 'POP1'
0 ;'DINOFLAG_E'
0 ;'DINOFLAG_N'
0 ;'DINOFLAG_P'
0 ;'MDIATOMS_E'
0 ;'MDIATOMS_N'
0 ;'MDIATOMS_P'
0 ;'MFLAGELA_E'
0 ;'MFLAGELA_N'
0 ;'MFLAGELA_P'
0 ;'PHAEOCYS_E'
0 ;'PHAEOCYS_N'
0 ;'PHAEOCYS_P'
0 ;'DetCS1'
0 ;'DetNS1'
0 ;'DetPS1'
0 ;'DetSiS1'
0 ;MALS
0 ;MALN
0 ;MALP
0 ;MALC
0 ;
0 ;
0 ;
0 ;

1  ; number of overridings

9845; first overriding
1 ;'Continuity'
7 ; 'OXY'
34 ; 'Salinity'
0.01  ; 'NH4'
0.01 ; 'NO3'
0.001; 'PO4'
0.1; 'Si'
0.1; 'Opal'
1 ;'POC1'
0.2; 'PON1'
0.01; 'POP1'
0 ;'DINOFLAG_E'
0 ;'DINOFLAG_N'
0 ;'DINOFLAG_P'
0 ;'MDIATOMS_E'
0 ;'MDIATOMS_N'
0 ;'MDIATOMS_P'
0 ;'MFLAGELA_E'
0 ;'MFLAGELA_N'
0 ;'MFLAGELA_P'
0 ;'PHAEOCYS_E'
0 ;'PHAEOCYS_N'
0 ;'PHAEOCYS_P'
0 ;'DetCS1'
0 ;'DetNS1'
0 ;'DetPS1'
0 ;'DetSiS1'
 0.159    ;'MALS'
 0.00159  ;'MALN'
 0.000159 ;'MALP'
 0.0954    ;'MALC'
 0.0;
 0.0;
 0.0;
 1.0;
