;CONSTANTS

; Taken from 24-02 version on P drive
; Not yet checked!!

;CONSTANTS 'TimMultBl'            DATA  2.00000e+000
;CONSTANTS 'Temp'                 DATA  1.50000e+001
;CONSTANTS 'Dry_THresh'            DATA  0.30
CONSTANTS 'NOTHREADS'             DATA  0
CONSTANTS 'SWBloomOut'            DATA  0.00000e+000
CONSTANTS 'FrAutMDI_E'            DATA  3.00000e-001
CONSTANTS 'FrAutMDI_N'            DATA  3.00000e-001
CONSTANTS 'FrAutMDI_P'            DATA  3.00000e-001
CONSTANTS 'FrAutMFL_E'            DATA  3.00000e-001
CONSTANTS 'FrAutMFL_N'            DATA  3.00000e-001
CONSTANTS 'FrAutMFL_P'            DATA  3.00000e-001
CONSTANTS 'FrAutDIN_E'            DATA  3.00000e-001
CONSTANTS 'FrAutDIN_N'            DATA  3.00000e-001
CONSTANTS 'FrAutDIN_P'            DATA  3.00000e-001
CONSTANTS 'FrAutPHA_E'            DATA  3.00000e-001
CONSTANTS 'FrAutPHA_N'            DATA  3.00000e-001
CONSTANTS 'FrAutPHA_P'            DATA  3.00000e-001
CONSTANTS 'FrDetMDI_E'            DATA  7.00000e-001
CONSTANTS 'FrDetMDI_N'            DATA  7.00000e-001
CONSTANTS 'FrDetMDI_P'            DATA  7.00000e-001
CONSTANTS 'FrDetMFL_E'            DATA  7.00000e-001
CONSTANTS 'FrDetMFL_N'            DATA  7.00000e-001
CONSTANTS 'FrDetMFL_P'            DATA  7.00000e-001
CONSTANTS 'FrDetDIN_E'            DATA  7.00000e-001
CONSTANTS 'FrDetDIN_N'            DATA  7.00000e-001
CONSTANTS 'FrDetDIN_P'            DATA  7.00000e-001
CONSTANTS 'FrDetPHA_E'            DATA  7.00000e-001
CONSTANTS 'FrDetPHA_N'            DATA  7.00000e-001
CONSTANTS 'FrDetPHA_P'            DATA  7.00000e-001
CONSTANTS 'ExtVlMDI_E'            DATA  2.40D-01
CONSTANTS 'ExtVlMDI_N'            DATA  2.10D-01
CONSTANTS 'ExtVlMDI_P'            DATA  2.10D-01
CONSTANTS 'ExtVlMFL_E'            DATA  2.50D-01
CONSTANTS 'ExtVlMFL_N'            DATA  2.25D-01
CONSTANTS 'ExtVlMFL_P'            DATA  2.25D-01
CONSTANTS 'ExtVlDIN_E'            DATA  2.00D-01
CONSTANTS 'ExtVlDIN_N'            DATA  1.75D-01
CONSTANTS 'ExtVlDIN_P'            DATA  1.75D-01
CONSTANTS 'ExtVlPHA_E'            DATA  4.50D-01
CONSTANTS 'ExtVlPHA_N'            DATA  4.125D-01
CONSTANTS 'ExtVlPHA_P'            DATA  4.125D-01
CONSTANTS 'DMCFMDI_E'             DATA  3.0
CONSTANTS 'DMCFMDI_N'             DATA  3.0
CONSTANTS 'DMCFMDI_P'             DATA  3.0
CONSTANTS 'DMCFMFL_E'             DATA  2.5
CONSTANTS 'DMCFMFL_N'             DATA  2.5
CONSTANTS 'DMCFMFL_P'             DATA  2.5
CONSTANTS 'DMCFDIN_E'             DATA  2.5
CONSTANTS 'DMCFDIN_N'             DATA  2.5
CONSTANTS 'DMCFDIN_P'             DATA  2.5
CONSTANTS 'DMCFPHA_E'             DATA  2.5
CONSTANTS 'DMCFPHA_N'             DATA  2.5
CONSTANTS 'DMCFPHA_P'             DATA  2.5
CONSTANTS 'NCRMDI_E'              DATA  0.25500
CONSTANTS 'NCRMDI_N'              DATA  0.12500
CONSTANTS 'NCRMDI_P'              DATA  0.15000
CONSTANTS 'NCRMFL_E'              DATA  0.20000
CONSTANTS 'NCRMFL_N'              DATA  0.14000
CONSTANTS 'NCRMFL_P'              DATA  0.20000
CONSTANTS 'NCRDIN_E'              DATA  0.16250
CONSTANTS 'NCRDIN_N'              DATA  0.12500
CONSTANTS 'NCRDIN_P'              DATA  0.13750
CONSTANTS 'NCRPHA_E'              DATA  0.18750
CONSTANTS 'NCRPHA_N'              DATA  0.13500
CONSTANTS 'NCRPHA_P'              DATA  0.18750
CONSTANTS 'PCRMDI_E'              DATA  0.03150
CONSTANTS 'PCRMDI_N'              DATA  0.01750
CONSTANTS 'PCRMDI_P'              DATA  0.01125
CONSTANTS 'PCRMFL_E'              DATA  0.02000
CONSTANTS 'PCRMFL_N'              DATA  0.01500
CONSTANTS 'PCRMFL_P'              DATA  0.01125
CONSTANTS 'PCRDIN_E'              DATA  0.01675
CONSTANTS 'PCRDIN_N'              DATA  0.01500
CONSTANTS 'PCRDIN_P'              DATA  0.01300
CONSTANTS 'PCRPHA_E'              DATA  0.02250
CONSTANTS 'PCRPHA_N'              DATA  0.02125
CONSTANTS 'PCRPHA_P'              DATA  0.01125
CONSTANTS 'SCRMDI_E'              DATA  0.44700
CONSTANTS 'SCRMDI_N'              DATA  0.28300
CONSTANTS 'SCRMDI_P'              DATA  0.28300
CONSTANTS 'SCRMFL_E'              DATA  0.00000
CONSTANTS 'SCRMFL_N'              DATA  0.00000
CONSTANTS 'SCRMFL_P'              DATA  0.00000
CONSTANTS 'SCRDIN_E'              DATA  0.00000
CONSTANTS 'SCRDIN_N'              DATA  0.00000
CONSTANTS 'SCRDIN_P'              DATA  0.00000
CONSTANTS 'SCRPHA_E'              DATA  0.00000
CONSTANTS 'SCRPHA_N'              DATA  0.00000
CONSTANTS 'SCRPHA_P'              DATA  0.00000
CONSTANTS 'ChlaCMDI_E'            DATA  0.0533
CONSTANTS 'ChlaCMDI_N'            DATA  0.0150
CONSTANTS 'ChlaCMDI_P'            DATA  0.0150
CONSTANTS 'ChlaCMFL_E'            DATA  0.0228
CONSTANTS 'ChlaCMFL_N'            DATA  0.0100
CONSTANTS 'ChlaCMFL_P'            DATA  0.0100
CONSTANTS 'ChlaCDIN_E'            DATA  0.0228
CONSTANTS 'ChlaCDIN_N'            DATA  0.0100
CONSTANTS 'ChlaCDIN_P'            DATA  0.0100
CONSTANTS 'ChlaCPHA_E'            DATA  0.0228
CONSTANTS 'ChlaCPHA_N'            DATA  0.0125
CONSTANTS 'ChlaCPHA_P'            DATA  0.0125
CONSTANTS 'PPMaxMDI_E'            DATA  0.070
CONSTANTS 'PPMaxMDI_N'            DATA  0.054
CONSTANTS 'PPMaxMDI_P'            DATA  0.054
CONSTANTS 'PPMaxMFL_E'            DATA  0.090
CONSTANTS 'PPMaxMFL_N'            DATA  0.075
CONSTANTS 'PPMaxMFL_P'            DATA  0.075
CONSTANTS 'PPMaxDIN_E'            DATA  0.132
CONSTANTS 'PPMaxDIN_N'            DATA  0.113
CONSTANTS 'PPMaxDIN_P'            DATA  0.113
CONSTANTS 'PPMaxPHA_E'            DATA  0.060
CONSTANTS 'PPMaxPHA_N'            DATA  0.055
CONSTANTS 'PPMaxPHA_P'            DATA  0.055
CONSTANTS 'TcPMxMDI_E'            DATA  -4.50
CONSTANTS 'TcPMxMDI_N'            DATA  -4.17
CONSTANTS 'TcPMxMDI_P'            DATA  -4.17
CONSTANTS 'TcPMxMFL_E'            DATA  -1.00
CONSTANTS 'TcPMxMFL_N'            DATA  -1.00
CONSTANTS 'TcPMxMFL_P'            DATA  -1.00
CONSTANTS 'TcPMxDIN_E'            DATA   5.50
CONSTANTS 'TcPMxDIN_N'            DATA   4.75
CONSTANTS 'TcPMxDIN_P'            DATA   4.75
CONSTANTS 'TcPMxPHA_E'            DATA  -8.00
CONSTANTS 'TcPMxPHA_N'            DATA  -8.00
CONSTANTS 'TcPMxPHA_P'            DATA  -8.00
CONSTANTS 'TFPMxMDI_E'            DATA  0.0
CONSTANTS 'TFPMxMDI_N'            DATA  0.0
CONSTANTS 'TFPMxMDI_P'            DATA  0.0
CONSTANTS 'TFPMxMFL_E'            DATA  0.0
CONSTANTS 'TFPMxMFL_N'            DATA  0.0
CONSTANTS 'TFPMxMFL_P'            DATA  0.0
CONSTANTS 'TFPMxDIN_E'            DATA  0.0
CONSTANTS 'TFPMxDIN_N'            DATA  0.0
CONSTANTS 'TFPMxDIN_P'            DATA  0.0
CONSTANTS 'TFPMxPHA_E'            DATA  0.0
CONSTANTS 'TFPMxPHA_N'            DATA  0.0
CONSTANTS 'TFPMxPHA_P'            DATA  0.0
CONSTANTS 'Mort0MDI_E'            DATA  0.070
CONSTANTS 'Mort0MDI_N'            DATA  0.080
CONSTANTS 'Mort0MDI_P'            DATA  0.080
CONSTANTS 'Mort0MFL_E'            DATA  0.070
CONSTANTS 'Mort0MFL_N'            DATA  0.080
CONSTANTS 'Mort0MFL_P'            DATA  0.080
CONSTANTS 'Mort0DIN_E'            DATA  0.070
CONSTANTS 'Mort0DIN_N'            DATA  0.080
CONSTANTS 'Mort0DIN_P'            DATA  0.080
CONSTANTS 'Mort0PHA_E'            DATA  0.070
CONSTANTS 'Mort0PHA_N'            DATA  0.080
CONSTANTS 'Mort0PHA_P'            DATA  0.080
CONSTANTS 'TcMrtMDI_E'            DATA  1.072
CONSTANTS 'TcMrtMDI_N'            DATA  1.085
CONSTANTS 'TcMrtMDI_P'            DATA  1.085
CONSTANTS 'TcMrtMFL_E'            DATA  1.072
CONSTANTS 'TcMrtMFL_N'            DATA  1.085
CONSTANTS 'TcMrtMFL_P'            DATA  1.085
CONSTANTS 'TcMrtDIN_E'            DATA  1.072
CONSTANTS 'TcMrtDIN_N'            DATA  1.085
CONSTANTS 'TcMrtDIN_P'            DATA  1.085
CONSTANTS 'TcMrtPHA_E'            DATA  1.072
CONSTANTS 'TcMrtPHA_N'            DATA  1.085
CONSTANTS 'TcMrtPHA_P'            DATA  1.085
CONSTANTS 'MRespMDI_E'            DATA  0.060
CONSTANTS 'MRespMDI_N'            DATA  0.060
CONSTANTS 'MRespMDI_P'            DATA  0.060
CONSTANTS 'MRespMFL_E'            DATA  0.060
CONSTANTS 'MRespMFL_N'            DATA  0.060
CONSTANTS 'MRespMFL_P'            DATA  0.060
CONSTANTS 'MRespDIN_E'            DATA  0.060
CONSTANTS 'MRespDIN_N'            DATA  0.060
CONSTANTS 'MRespDIN_P'            DATA  0.060
CONSTANTS 'MRespPHA_E'            DATA  0.060
CONSTANTS 'MRespPHA_N'            DATA  0.060
CONSTANTS 'MRespPHA_P'            DATA  0.060
CONSTANTS 'TcRspMDI_E'            DATA  1.066
CONSTANTS 'TcRspMDI_N'            DATA  1.066
CONSTANTS 'TcRspMDI_P'            DATA  1.066
CONSTANTS 'TcRspMFL_E'            DATA  1.066
CONSTANTS 'TcRspMFL_N'            DATA  1.066
CONSTANTS 'TcRspMFL_P'            DATA  1.066
CONSTANTS 'TcRspDIN_E'            DATA  1.066
CONSTANTS 'TcRspDIN_N'            DATA  1.066
CONSTANTS 'TcRspDIN_P'            DATA  1.066
CONSTANTS 'TcRspPHA_E'            DATA  1.066
CONSTANTS 'TcRspPHA_N'            DATA  1.066
CONSTANTS 'TcRspPHA_P'            DATA  1.066
  CONSTANTS 'MrtExMDI_E'            DATA  0.0
  CONSTANTS 'MrtExMDI_N'            DATA  0.0
  CONSTANTS 'MrtExMDI_P'            DATA  0.0
  CONSTANTS 'MrtExMFL_E'            DATA  0.0
  CONSTANTS 'MrtExMFL_N'            DATA  0.0
  CONSTANTS 'MrtExMFL_P'            DATA  0.0
  CONSTANTS 'MrtExDIN_E'            DATA  0.0
  CONSTANTS 'MrtExDIN_N'            DATA  0.0
  CONSTANTS 'MrtExDIN_P'            DATA  0.0
  CONSTANTS 'MrtExPHA_E'            DATA  0.0
  CONSTANTS 'MrtExPHA_N'            DATA  0.0
  CONSTANTS 'MrtExPHA_P'            DATA  0.0
  CONSTANTS 'MrtExULS_E'            DATA  0.0
  CONSTANTS 'MrtExULS_N'            DATA  0.0
  CONSTANTS 'MrtExULS_P'            DATA  0.0
  CONSTANTS 'MrtExULF_E'            DATA  0.0
  CONSTANTS 'MrtExULF_N'            DATA  0.0
  CONSTANTS 'MrtExULF_P'            DATA  0.0
;  CONSTANTS 'Mort2MDI_E'            DATA  0.0
;  CONSTANTS 'Mort2MDI_N'            DATA  0.0
;  CONSTANTS 'Mort2MDI_P'            DATA  0.0
;  CONSTANTS 'Mort2MFL_E'            DATA  0.0
;  CONSTANTS 'Mort2MFL_N'            DATA  0.0
;  CONSTANTS 'Mort2MFL_P'            DATA  0.0
;  CONSTANTS 'Mort2DIN_E'            DATA  0.0
;  CONSTANTS 'Mort2DIN_N'            DATA  0.0
;  CONSTANTS 'Mort2DIN_P'            DATA  0.0
;  CONSTANTS 'Mort2PHA_E'            DATA  0.0
;  CONSTANTS 'Mort2PHA_N'            DATA  0.0
;  CONSTANTS 'Mort2PHA_P'            DATA  0.0
;  CONSTANTS 'MrtB1MDI_E'            DATA  0.20E-02
;  CONSTANTS 'MrtB1MDI_N'            DATA  0.20E-02
;  CONSTANTS 'MrtB1MDI_P'            DATA  0.20E-02
;  CONSTANTS 'MrtB1MFL_E'            DATA  0.20E-02
;  CONSTANTS 'MrtB1MFL_N'            DATA  0.20E-02
;  CONSTANTS 'MrtB1MFL_P'            DATA  0.20E-02
;  CONSTANTS 'MrtB1DIN_E'            DATA  0.20E-02
;  CONSTANTS 'MrtB1DIN_N'            DATA  0.20E-02
;  CONSTANTS 'MrtB1DIN_P'            DATA  0.20E-02
;  CONSTANTS 'MrtB1PHA_E'            DATA  0.20E-02
;  CONSTANTS 'MrtB1PHA_N'            DATA  0.20E-02
;  CONSTANTS 'MrtB1PHA_P'            DATA  0.20E-02
;  CONSTANTS 'MrtB2MDI_E'            DATA  8000.0
;  CONSTANTS 'MrtB2MDI_N'            DATA  8000.0
;  CONSTANTS 'MrtB2MDI_P'            DATA  8000.0
;  CONSTANTS 'MrtB2MFL_E'            DATA  8000.0
;  CONSTANTS 'MrtB2MFL_N'            DATA  8000.0
;  CONSTANTS 'MrtB2MFL_P'            DATA  8000.0
;  CONSTANTS 'MrtB2DIN_E'            DATA  8000.0
;  CONSTANTS 'MrtB2DIN_N'            DATA  8000.0
;  CONSTANTS 'MrtB2DIN_P'            DATA  8000.0
;  CONSTANTS 'MrtB2PHA_E'            DATA  8000.0
;  CONSTANTS 'MrtB2PHA_N'            DATA  8000.0
;  CONSTANTS 'MrtB2PHA_P'            DATA  8000.0
CONSTANTS 'RcDetC'                DATA  0.12
CONSTANTS 'TcDetC'                DATA  1.11000e+000
CONSTANTS 'TauCSDetC'             DATA  1.00000e-001 ;0.0
CONSTANTS 'MinDepth'              DATA  1.00000e-001
CONSTANTS 'SecchiExt1'            DATA  1.35000e+000
CONSTANTS 'RcDetCS1'              DATA  1.50000e-002
CONSTANTS 'TcBMDetC'              DATA  1.11000e+000
CONSTANTS 'RcDetN'                DATA  1.20000e-001
CONSTANTS 'TcDetN'                DATA  1.11000e+000
CONSTANTS 'RcDetNS1'              DATA  2.50000e-002
CONSTANTS 'TcBMDetN'              DATA  1.11000e+000
CONSTANTS 'RcDetP'                DATA  0.08
CONSTANTS 'TcDetP'                DATA  1.11000e+000
CONSTANTS 'RcDetPS1'              DATA  4.00000e-002
CONSTANTS 'TcBMDetP'              DATA  1.15
CONSTANTS 'TcBMDetPS1'            DATA  1.15000e+000
CONSTANTS 'RcDetSi'               DATA  8.00000e-002
CONSTANTS 'TcDetSi'               DATA  1.04700e+000
CONSTANTS 'RcDetSiS1'             DATA  1.00000e-002
CONSTANTS 'TcBMDetSi'             DATA  1.04700e+000
CONSTANTS 'TcNit'                 DATA  1.11000e+000
CONSTANTS 'RcNit'                 DATA  7.00000e-002
CONSTANTS 'pH'                    DATA  8.10000e+000
CONSTANTS 'RcDenSed'              DATA  0.00000e+000
CONSTANTS 'TcDenWat'              DATA  1.11000e+000
CONSTANTS 'COXDEN'                DATA  1.01000e+002
CONSTANTS 'RcDenWat'              DATA  6.00000e-003
CONSTANTS 'OOXDEN'                DATA  1.00000e+002
CONSTANTS 'SWAdsP'                DATA  1.0   ;0.0
CONSTANTS 'KdPO4AAP'              DATA  1.00000e-001 ;  0.0
CONSTANTS 'MaxPO4AAP'             DATA  0.15 ; 5.00000e-003 ;  0.0
CONSTANTS 'RcAdPO4AAP'            DATA  0.00000e+000
CONSTANTS 'TaucS'                 DATA  1.00000e-001 ; 0.0
CONSTANTS 'SWRear'                DATA  9.00000e+000
CONSTANTS 'KLRear'                DATA  4.00000e+000
CONSTANTS 'RcBOD'                 DATA  3.00000e-001
CONSTANTS 'AlgFrBOD'              DATA  5.00000e-001
CONSTANTS 'fSODaut'               DATA  0.00000e+000
CONSTANTS 'RcSOD'                 DATA  1.00000e-001  ;  0.0
CONSTANTS 'TcSOD'                 DATA  1.04000e+000  ;  0.0
CONSTANTS 'ExtVlIM1'              DATA  2.50000e-002
CONSTANTS 'ExtVlIM2'              DATA  2.50000e-002
CONSTANTS 'ExtVlBak'              DATA  8.00000e-002
CONSTANTS 'SWDepAve'              DATA  1.00000e+000
CONSTANTS 'Latitude'              DATA  5.21000e+001
CONSTANTS 'RefDay'                DATA  0.00000e+000
CONSTANTS 'SWTau'                 DATA  1.00000e+000 ;0.0
CONSTANTS 'ZResDM'                DATA  2.50000e+004
CONSTANTS 'TaucRS1DM'             DATA  2.00000e-001 ; 0.0
CONSTANTS 'PeriodVTRA'            DATA  2.40000e+001
CONSTANTS 'VBurDMS1'              DATA  2.50000e-003
CONSTANTS 'MaxVeloc'              DATA  0.00000e+000
CONSTANTS 'OON'                   DATA  0.00000e+000
CONSTANTS 'ExtVlDetC'             DATA  1.00000e-001
CONSTANTS 'FETCH'                 DATA  1.00000e+003 ; 0.0
CONSTANTS 'InitDepth'             DATA  -1.00000e+000
CONSTANTS 'SwChezy'               DATA  1.00000e+000  ;
CONSTANTS 'TaucSIM1'              DATA  1.00000e-001  ;
CONSTANTS 'V0SedIM1'              DATA  0.00000e+000
CONSTANTS 'COXNit'                DATA  -1.00000e+000
CONSTANTS 'CRTemp'                DATA  -1.00000e+000
CONSTANTS 'CTMin'                 DATA  -1.00000e+000
CONSTANTS 'CTNit'                 DATA  -1.00000e+000
CONSTANTS 'ExtVLSal0'             DATA  9.70000e-001
CONSTANTS 'IM1S1'                 DATA  1.00000e+007
CONSTANTS 'MaxThS1'               DATA  999999
CONSTANTS 'NCMinLimH'             DATA  1.50000e-001
CONSTANTS 'NCMinLimL'             DATA  1.00000e-001
CONSTANTS 'nDetC'                 DATA  0.00000e+000
CONSTANTS 'OOXNit'                DATA  0.00000e+000
CONSTANTS 'PCMinLimH'             DATA  1.50000e-002
CONSTANTS 'PCMinLimL'             DATA  1.00000e-002
CONSTANTS 'PorS1'                 DATA  3.00000e-001
CONSTANTS 'RcDetCHigh'            DATA  1.80000e-001
CONSTANTS 'RcDetNHigh'            DATA  1.80000e-001
CONSTANTS 'RcDetPHigh'            DATA  1.80000e-001
CONSTANTS 'RcDetSHigh'            DATA  8.00000e-002
CONSTANTS 'SiCMinLimH'            DATA  0.02
CONSTANTS 'SiCMinLimL'            DATA  0.01
CONSTANTS 'SWSediment'            DATA  1.00000e+000
CONSTANTS 'tau'                   DATA -1.00000e+000
CONSTANTS 'TCSed'                 DATA  1.00000e+000
CONSTANTS 'V0SedDetC'             DATA  1.50000e+000
CONSTANTS 'V0SedDIN_E'            DATA  0.00000e+000
CONSTANTS 'V0SedDIN_N'            DATA  0.00000e+000
CONSTANTS 'V0SedDIN_P'            DATA  0.00000e+000
CONSTANTS 'V0SedMDI_E'            DATA  5.00000e-001
CONSTANTS 'V0SedMDI_N'            DATA  1.00000e+000
CONSTANTS 'V0SedMDI_P'            DATA  1.00000e+000
CONSTANTS 'V0SedMFL_E'            DATA  0.00000e+000
CONSTANTS 'V0SedMFL_N'            DATA  5.00000e-001
CONSTANTS 'V0SedMFL_P'            DATA  5.00000e-001
CONSTANTS 'V0SedPHA_E'            DATA  0.00000e+000
CONSTANTS 'V0SedPHA_N'            DATA  5.00000e-001
CONSTANTS 'V0SedPHA_P'            DATA  5.00000e-001
CONSTANTS 'V0SedULS_E'            DATA  5.00000e-001
CONSTANTS 'V0SedULS_N'            DATA  1.00000e+000
CONSTANTS 'V0SedULS_P'            DATA  1.00000e+000
CONSTANTS 'V0SedULF_E'            DATA  0.00000e+000
CONSTANTS 'V0SedULF_N'            DATA  0.00000e+000
CONSTANTS 'V0SedULF_P'            DATA  0.00000e+000
CONSTANTS 'AAP'                   DATA  0.00000e+000
CONSTANTS 'ScaleVDisp'            DATA  1.00000e+000
CONSTANTS 'ACTIVE_TOTDEPTH'       DATA  1.00000e+000
CONSTANTS 'CLOSE_ERR'             DATA  1.00000e+000
CONSTANTS 'MaxIter'               DATA  1.00000e+002
CONSTANTS 'Tolerance'             DATA  1.00000e-007
CONSTANTS 'Iteration Report'      DATA  0.00000e+000
CONSTANTS 'ONLY_ACTIVE'           DATA  1.00000e+000
CONSTANTS 'ACTIVE_VarSal'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_BLOOM_P'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_PHY_BLO_P'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_WM_DetC'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_SedDetC'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_Res_DetC'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_Secchi'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_BMS1_DetC'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_SedPhBlo_P'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_BurS1_DetC'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_WM_DetN'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_SedN_Det'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_ResN_Det'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_BMS1_DetN'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_BurS1N_Det'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_WM_DetP'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_BMS1_DetP'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_WM_DetSi'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_BMS1_DetSi'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_Nitrif_NH4'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_xxxNH3free'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_DenSed_NO3'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_DenWat_NO3'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_AdsPO4AAP'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDALG'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_RearOXY'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_BODCOD'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_xxxSedOXYDem'   DATA  1.00000e+000
CONSTANTS 'ACTIVE_PosOXY'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_Chloride'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_Extinc_VL'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_EXTINABVLP'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalcRad'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_DynDepth'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_DepAve'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_Daylength'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_vtrans'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_VertDisp'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_Tau'            DATA  1.00000e+000
CONSTANTS 'ACTIVE_Res_DM'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_S1_Comp'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_Bur_DM'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_Veloc'          DATA  1.00000e+000
CONSTANTS 'ACTIVE_SaturOXY'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_TotDepth'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_POC_Dyn'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_ExtPODVL'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_xxxWave'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_xxxChezy'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_S2_Comp'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_Sum_Sedim'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_Sed_IM1'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_SedPODyn'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_Grd_Rho'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_Grd_Vel'        DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVS_IM1'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_Compos'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVS_DetC'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSAlg'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SedAlg'         DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSDIN_E'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSDIN_N'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSDIN_P'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSMDI_E'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSMDI_N'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSMDI_P'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSMFL_E'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSMFL_N'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSMFL_P'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSPHA_E'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSPHA_N'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_CalVSPHA_P'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_EXTINABVL'      DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDDIN_E'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDDIN_N'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDDIN_P'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDMDI_E'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDMDI_N'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDMDI_P'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDMFL_E'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDMFL_N'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDMFL_P'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDPHA_E'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDPHA_N'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_SEDPHA_P'       DATA  1.00000e+000
CONSTANTS 'ACTIVE_AtmDep_NH4'     DATA  1.00000e+000
CONSTANTS 'ACTIVE_AtmDep_NO3'     DATA  1.00000e+000

; Added by Lilith Kramer 2016-nov-16; ULVA constants copy from marine diatoms
CONSTANTS 'ACTIVE_UlvaFix_P'      DATA 1.00000E+000
CONSTANTS 'ChlaCULF_E'            DATA 5.33000E-002
CONSTANTS 'ChlaCULF_N'            DATA 1.50000E-002
CONSTANTS 'ChlaCULF_P'            DATA 1.50000E-002
CONSTANTS 'DMCFULF_E'             DATA 3.00000E+000
CONSTANTS 'DMCFULF_N'             DATA 3.00000E+000
CONSTANTS 'DMCFULF_P'             DATA 3.00000E+000
CONSTANTS 'ExtVlULF_E'            DATA 0.00000E+000 ;DATA 2.40000E-001
CONSTANTS 'ExtVlULF_N'            DATA 0.00000E+000 ;DATA 2.10000E-001
CONSTANTS 'ExtVlULF_P'            DATA 0.00000E+000 ;DATA 2.10000E-001
CONSTANTS 'FrAutULF_E'            DATA 3.00000E-001
CONSTANTS 'FrAutULF_N'            DATA 3.00000E-001
CONSTANTS 'FrAutULF_P'            DATA 3.00000E-001
CONSTANTS 'FrDetULF_E'            DATA 7.00000E-001
CONSTANTS 'FrDetULF_N'            DATA 7.00000E-001
CONSTANTS 'FrDetULF_P'            DATA 7.00000E-001
CONSTANTS 'Mort0ULF_E'            DATA 7.00000E-002
CONSTANTS 'Mort0ULF_N'            DATA 8.00000E-002
CONSTANTS 'Mort0ULF_P'            DATA 8.00000E-002
CONSTANTS 'MRespULF_E'            DATA 6.00000E-002
CONSTANTS 'MRespULF_N'            DATA 6.00000E-002
CONSTANTS 'MRespULF_P'            DATA 6.00000E-002
CONSTANTS 'NCRULF_E'              DATA 2.55100E-001
CONSTANTS 'NCRULF_N'              DATA 1.25100E-001
CONSTANTS 'NCRULF_P'              DATA 1.50100E-001
CONSTANTS 'PCRULF_E'              DATA 3.15100E-002
CONSTANTS 'PCRULF_N'              DATA 1.75100E-002
CONSTANTS 'PCRULF_P'              DATA 1.12600E-002
CONSTANTS 'PPMaxULF_E'            DATA 7.00000E-002
CONSTANTS 'PPMaxULF_N'            DATA 5.40000E-002
CONSTANTS 'PPMaxULF_P'            DATA 5.40000E-002
CONSTANTS 'SCRULF_E'              DATA 4.47100E-001
CONSTANTS 'SCRULF_N'              DATA 2.83100E-001
CONSTANTS 'SCRULF_P'              DATA 2.83100E-001
CONSTANTS 'TauCrUlva'             DATA 1.00000E+000
CONSTANTS 'TcMrtULF_E'            DATA 1.07200E+000
CONSTANTS 'TcMrtULF_N'            DATA 1.08500E+000
CONSTANTS 'TcMrtULF_P'            DATA 1.08500E+000
CONSTANTS 'TcPMxULF_E'            DATA -4.5000E+000
CONSTANTS 'TcPMxULF_N'            DATA -4.1700E+000
CONSTANTS 'TcPMxULF_P'            DATA -4.1700E+000
CONSTANTS 'TcRspULF_E'            DATA 1.06600E+000
CONSTANTS 'TcRspULF_N'            DATA 1.06600E+000
CONSTANTS 'TcRspULF_P'            DATA 1.06600E+000
CONSTANTS 'TFPMxULF_E'            DATA 0.00000E+000
CONSTANTS 'TFPMxULF_N'            DATA 0.00000E+000
CONSTANTS 'TFPMxULF_P'            DATA 0.00000E+000
CONSTANTS 'SDMIXULF_E'            DATA -1
CONSTANTS 'SDMIXULF_N'            DATA -1
CONSTANTS 'SDMIXULF_P'            DATA -1
CONSTANTS 'FixULF_E'              DATA -1
CONSTANTS 'FixULF_N'              DATA -2
CONSTANTS 'FixULF_P'              DATA -3
CONSTANTS 'ChlaCULS_E'            DATA 5.33000E-002
CONSTANTS 'ChlaCULS_N'            DATA 1.50000E-002
CONSTANTS 'ChlaCULS_P'            DATA 1.50000E-002
CONSTANTS 'DMCFULS_E'             DATA 3.00000E+000
CONSTANTS 'DMCFULS_N'             DATA 3.00000E+000
CONSTANTS 'DMCFULS_P'             DATA 3.00000E+000
CONSTANTS 'ExtVlULS_E'            DATA 2.40000E-001
CONSTANTS 'ExtVlULS_N'            DATA 2.10000E-001
CONSTANTS 'ExtVlULS_P'            DATA 2.10000E-001
CONSTANTS 'FrAutULS_E'            DATA 3.00000E-001
CONSTANTS 'FrAutULS_N'            DATA 3.00000E-001
CONSTANTS 'FrAutULS_P'            DATA 3.00000E-001
CONSTANTS 'FrDetULS_E'            DATA 7.00000E-001
CONSTANTS 'FrDetULS_N'            DATA 7.00000E-001
CONSTANTS 'FrDetULS_P'            DATA 7.00000E-001
CONSTANTS 'Mort0ULS_E'            DATA 7.00000E-002
CONSTANTS 'Mort0ULS_N'            DATA 8.00000E-002
CONSTANTS 'Mort0ULS_P'            DATA 8.00000E-002
CONSTANTS 'MRespULS_E'            DATA 6.00000E-002
CONSTANTS 'MRespULS_N'            DATA 6.00000E-002
CONSTANTS 'MRespULS_P'            DATA 6.00000E-002
CONSTANTS 'NCRULS_E'              DATA 2.55100E-001
CONSTANTS 'NCRULS_N'              DATA 1.25100E-001
CONSTANTS 'NCRULS_P'              DATA 1.50100E-001
CONSTANTS 'PCRULS_E'              DATA 3.15100E-002
CONSTANTS 'PCRULS_N'              DATA 1.75100E-002
CONSTANTS 'PCRULS_P'              DATA 1.12600E-002
CONSTANTS 'PPMaxULS_E'            DATA 7.00000E-002
CONSTANTS 'PPMaxULS_N'            DATA 5.40000E-002
CONSTANTS 'PPMaxULS_P'            DATA 5.40000E-002
CONSTANTS 'SCRULS_E'              DATA 4.47100E-001
CONSTANTS 'SCRULS_N'              DATA 2.83100E-001
CONSTANTS 'SCRULS_P'              DATA 2.83100E-001
CONSTANTS 'TcMrtULS_E'            DATA 1.07200E+000
CONSTANTS 'TcMrtULS_N'            DATA 1.08500E+000
CONSTANTS 'TcMrtULS_P'            DATA 1.08500E+000
CONSTANTS 'TcPMxULS_E'            DATA -4.5000E+000
CONSTANTS 'TcPMxULS_N'            DATA -4.1700E+000
CONSTANTS 'TcPMxULS_P'            DATA -4.1700E+000
CONSTANTS 'TcRspULS_E'            DATA 1.06600E+000
CONSTANTS 'TcRspULS_N'            DATA 1.06600E+000
CONSTANTS 'TcRspULS_P'            DATA 1.06600E+000
CONSTANTS 'TFPMxULS_E'            DATA 0.00000E+000
CONSTANTS 'TFPMxULS_N'            DATA 0.00000E+000
CONSTANTS 'TFPMxULS_P'            DATA 0.00000E+000
CONSTANTS 'SDMIXULS_E'            DATA 1
CONSTANTS 'SDMIXULS_N'            DATA 1
CONSTANTS 'SDMIXULS_P'            DATA 1
CONSTANTS 'FixULS_E'              DATA 1
CONSTANTS 'FixULS_N'              DATA 2
CONSTANTS 'FixULS_P'              DATA 3
;CONSTANTS 'TauCr'                 DATA 999.00000E+000 ; anders geen sedimentatie meer!

; Grazing added Lilith Kramer 2016-11-14 - copied from WZS28 ; Grazing added Hans Los - copied from Cascade model with additions for UlvaF
                CONSTANTS        'xACTIVE_CONSBL'   DATA  1.00000e+000 ; ACTIVE_CONSBL needed for grazing
                CONSTANTS        'MALGPR01'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl E                [-]
                CONSTANTS        'MALGPR02'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl N                [-]
                CONSTANTS        'MALGPR03'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl P                [-]
                CONSTANTS        'MALGPR04'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat E                  [-]
                CONSTANTS        'MALGPR05'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat-N                  [-]
                CONSTANTS        'MALGPR06'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat-P                  [-]
                CONSTANTS        'MALGPR07'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-E                  [-]
                CONSTANTS        'MALGPR08'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-N                  [-]
                CONSTANTS        'MALGPR09'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-P                  [-]
                CONSTANTS        'MALGPR10'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-E                 [-]
                CONSTANTS        'MALGPR11'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-N                 [-]
                CONSTANTS        'MALGPR12'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-P                 [-]
                CONSTANTS        'MALGPR13'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-E                 [-]
                CONSTANTS        'MALGPR14'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-N                 [-]
                CONSTANTS        'MALGPR15'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-P                 [-]
                CONSTANTS        'MALGPR16'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-E                 [-]
                CONSTANTS        'MALGPR17'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-N                 [-]
                CONSTANTS        'MALGPR18'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-P                 [-]
                CONSTANTS        'MDETPR'       DATA     1.00000E+000 ; MDETPR          Prefernce of grazer of Detritus                 [-]  ; LK 2016-nov-15 back to default value, used to be 5.0
                CONSTANTS        'MGRZMO'       DATA     1.00000E-001 ; MGRZMO          Monod term filtration rate Mussel               [gC/m3]
                CONSTANTS        'MGRZRM'       DATA     1.00000E-001 ; MGRZRM          Maximum daily uptake Mussel                     [mgC/mgC/d]
                CONSTANTS        'MGRZFM'       DATA     5.00000E-002 ; MGRZFM          Maximum filtration velocity Mussel              [m3/gC/d]
                CONSTANTS        'MTMPFM'       DATA     4.00000E-002 ; MTMPFM          Tempearture coefficient Mussel filtration       [1/oC]
                CONSTANTS        'MTMPRM'       DATA     4.00000E-002 ; MTMPFM          Tempearture coefficient Mussel feeding rate     [1/oC]
                CONSTANTS        'MGRZMM'       DATA     0.20000E-000 ; MGRZMM          Maximum relative mortality Mussel               [1/d]
                                CONSTANTS        'MGRZMC'       DATA     0.01         ; MGRZMC          Minimum input concentration of Mussel           [gC/m3] ; LK 2016-nov-15 added for clarity
                CONSTANTS        'MGRZGM'       DATA     0.20000E-000 ; MGRZGM          Maximum relative Growth Mussel                  [1/d]
                CONSTANTS        'MGRZSE'       DATA     0.00500E+000 ; MGRZSE          Standaard respiration coefficient Mussel        [1/d]
                CONSTANTS        'MGRZRE'       DATA     0.20000E+000 ; MGRZRE          Maintenance respiration coefficient Mussel      [-]
                CONSTANTS        'MUnitSW'      DATA     1.00000E+000 ; MUnitSW         Use gC/m3 (0) or gC/m2 (1) for Mussels          [-]
                CONSTANTS        'Zooplank'     DATA     0.00000E+000 ; no zooplankton

; DEB constants   added by Tineke on basis of Volkerak.org
; NB in the Wadden Sea these values are overwritten by a PARAMETER FUNCTION by mussel values
CONSTANTS 'ACTIVE_DEBGRZ_M'       DATA  1.00000e+000
CONSTANTS 'M_SwV1'            DATA        1.00000e+000 ; switch (0 for isomorphs 0 for V1morphs)
;CONSTANTS 'M_Lref'            DATA       10.00000e+000 ; ref length of DEB ensis  (only for V1morphs)
CONSTANTS 'M_Dummy'           DATA        1.00000e+000 ; dummy constant for DEB ensis
;CONSTANTS 'M_Vb'              DATA        0.290000e-07 ; volume at birth individual DEB ensis
;CONSTANTS 'M_Vp'              DATA        0.475100E-00 ; volume at start of repro stage ind DEB ensis
;CONSTANTS 'M_shape'           DATA        0.178600     ; shape coefficient of DEB ensis
;CONSTANTS 'M_Em'              DATA        4005.26      ; maximum storage density of DEB ensis
;CONSTANTS 'M_Eg'              DATA        3415.00      ; volume-spec costs for growth of DEB ensis
;CONSTANTS 'M_Pm'              DATA        45.7000      ; respiration rate constant of DEB ensis
;CONSTANTS 'M_JXm'             DATA        200.000      ; max ingestion rate of DEB ensis
CONSTANTS 'M_kappaI'          DATA        0.75000      ; ingestion efficiency of DEB ensis
CONSTANTS 'M_kappaA'          DATA        1.000000     ; assimilation efficiency of DEB ensis
;CONSTANTS 'M_kappa'           DATA        0.973100     ; fraction of energy spent on growth DEB ensis
;CONSTANTS 'M_kappaR'          DATA        0.950000     ; fraction of energy spent on gonads DEB ensis
;CONSTANTS 'M_Ta'              DATA        6000.00      ; arrhenius temperature of DEB ensis
;CONSTANTS 'M_Tah'             DATA        47126.0      ; arr temp for upper boundary DEB ensis
;CONSTANTS 'M_Tal'             DATA        51154.0      ; arr temp for lower boundary DEB ensis
;CONSTANTS 'M_Th'              DATA        306.000      ; upper boundary of tolerance range of DEB ensis
;CONSTANTS 'M_Tl'              DATA        278.000      ; lower boundary of tolerance range of DEB ensis
;CONSTANTS 'M_GSIupr'          DATA        0.025000     ; minimum GSI for spawning of DEB ensis
;CONSTANTS 'M_GSIlwr'          DATA        0.000500     ; minimum GSI while spawning of DEB ensis
CONSTANTS 'M_DoSpawn'         DATA        0.00000      ; indication of spawning of DEB ensis
CONSTANTS 'M_rSpawn'          DATA        0.200000E-01 ; spawning rate of DEB ensis
;CONSTANTS 'M_MinSTmp'         DATA        18.4000      ; minimum temperature for spawning of DEB ensis
;CONSTANTS 'M_Xk'              DATA        0.075000     ; halfrate const for food of DEB ensis
;CONSTANTS 'M_Yk'              DATA        100.000      ; halfrate const for TIM of DEB ensis
;CONSTANTS 'M_rMor'            DATA        0.050000E-00 ; reference mortality rate of DEB ensis
CONSTANTS 'M_cMor'            DATA        0.00000      ; length coefficient harvesting rate DEB ensis
CONSTANTS 'M_rHrv'            DATA        0.00000      ; reference rate of harvesting of DEB ensis
CONSTANTS 'M_cHrv'            DATA        0.00000      ; length coefficient harvesting rate DEB ensis
CONSTANTS 'M_cEC'             DATA        0.355555E-04 ; energy to carbon conversion of DEB ensis
CONSTANTS 'M_cVC'             DATA        0.480000E-01 ; volume to carbon conversion of DEB ensis
CONSTANTS 'M_cAFWC'           DATA        0.400000     ; AFD weight to carbon conv of DEB ensis
;CONSTANTS 'M_cWWC'            DATA        0.224000E-01 ; wetweight to carbon conv of DEB ensis
CONSTANTS 'M_TC'              DATA        1.00000e+000 ; C:C ratio of DEB ensis
CONSTANTS 'M_TN'              DATA        0.181800     ; N:C ratio of DEB ensis
CONSTANTS 'M_TP'              DATA        0.263000E-01 ; P:C ratio of DEB ensis
CONSTANTS 'M_TSi'             DATA        0.00000      ; Si:C ratio of DEB ensis
CONSTANTS 'M_FrDetS1'         DATA        1.00000e+000 ; fraction of DEB ensis detritus into sediment
CONSTANTS 'M_SWBen'           DATA        1.00000e+000 ; SWBen specifies the location of the grazers, pelagic = 0, benthic = 1, suspended = 2
CONSTANTS 'M_SFSusp'          DATA        1.00000e+000 ; DEB ensis pref suspension over deposit feeding
CONSTANTS 'M_PrDet'           DATA        0.00000      ; DEB ensis preference for DetC or POC1
CONSTANTS 'M_PrDetS1'         DATA        0.00000      ; DEB ensis preference for DetCS1
CONSTANTS 'M_FFDet'           DATA        0.500000     ; Faecal fraction of DetC for DEB ensis
CONSTANTS 'M_FFDetS1'         DATA        0.500000     ; Faecal fraction of DetCS1 for DEB ensis
CONSTANTS 'M_PrAlg01'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl E                [-]
CONSTANTS 'M_PrAlg02'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl N                [-]
CONSTANTS 'M_PrAlg03'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl P                [-]
CONSTANTS 'M_PrAlg04'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat E                  [-]
CONSTANTS 'M_PrAlg05'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat-N                  [-]
CONSTANTS 'M_PrAlg06'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat-P                  [-]
CONSTANTS 'M_PrAlg07'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-E                  [-]
CONSTANTS 'M_PrAlg08'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-N                  [-]
CONSTANTS 'M_PrAlg09'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-P                  [-]
CONSTANTS 'M_PrAlg10'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-E                 [-]
CONSTANTS 'M_PrAlg11'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-N                 [-]
CONSTANTS 'M_PrAlg12'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-P                 [-]
CONSTANTS 'M_PrAlg13'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-E                 [-]
CONSTANTS 'M_PrAlg14'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-N                 [-]
CONSTANTS 'M_PrAlg15'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-P                 [-]
CONSTANTS 'M_PrAlg16'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-E                 [-]
CONSTANTS 'M_PrAlg17'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-N                 [-]
CONSTANTS 'M_PrAlg18'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-P                 [-]


;Grazer3; DEB constants   added by Tineke on basis of Volkerak.org
; NB in the Wadden Sea these values are overwritten by a PARAMETER FUNCTION by mussel values
CONSTANTS 'ACTIVE_DEBGRZ_G3'   DATA  1.00000e+000
;CONSTANTS 'G3_Lref'            DATA        10.00000e+000 ; ref length of DEB ensis  (only for V1morphs)
CONSTANTS 'G3_Dummy'           DATA         1.00000e+000 ; dummy constant for DEB ensis
;CONSTANTS 'G3_Vb'              DATA         0.290000e-07 ; volume at birth individual DEB ensis
;CONSTANTS 'G3_Vp'              DATA         0.475100E-00 ; volume at start of repro stage ind DEB ensis
;CONSTANTS 'G3_shape'           DATA         0.178600     ; shape coefficient of DEB ensis
;CONSTANTS 'G3_Em'              DATA         4005.26      ; maximum storage density of DEB ensis
;CONSTANTS 'G3_Eg'              DATA         3415.00      ; volume-spec costs for growth of DEB ensis
;CONSTANTS 'G3_Pm'              DATA         45.7000      ; respiration rate constant of DEB ensis
;CONSTANTS 'G3_JXm'             DATA         200.000      ; max ingestion rate of DEB ensis
CONSTANTS 'G3_kappaI'          DATA         0.75000      ; ingestion efficiency of DEB ensis
CONSTANTS 'G3_kappaA'          DATA         1.000000     ; assimilation efficiency of DEB ensis
;CONSTANTS 'G3_kappa'           DATA         0.973100     ; fraction of energy spent on growth DEB ensis
CONSTANTS 'G3_kappaR'          DATA         0.950000     ; fraction of energy spent on gonads DEB ensis
;CONSTANTS 'G3_Ta'              DATA         6000.00      ; arrhenius temperature of DEB ensis
;CONSTANTS 'G3_Tah'             DATA         47126.0      ; arr temp for upper boundary DEB ensis
;CONSTANTS 'G3_Tal'             DATA         51154.0      ; arr temp for lower boundary DEB ensis
;CONSTANTS 'G3_Th'              DATA         306.000      ; upper boundary of tolerance range of DEB ensis
;CONSTANTS 'G3_Tl'              DATA         278.000      ; lower boundary of tolerance range of DEB ensis
;CONSTANTS 'G3_GSIupr'          DATA         0.025000     ; minimum GSI for spawning of DEB ensis
;CONSTANTS 'G3_GSIlwr'          DATA         0.000500     ; minimum GSI while spawning of DEB ensis
CONSTANTS 'G3_DoSpawn'         DATA         0.00000      ; indication of spawning of DEB ensis
CONSTANTS 'G3_rSpawn'          DATA         0.200000E-01 ; spawning rate of DEB ensis
;CONSTANTS 'G3_MinSTmp'         DATA         18.4000      ; minimum temperature for spawning of DEB ensis
;CONSTANTS 'G3_Xk'              DATA         0.075000     ; halfrate const for food of DEB ensis
;CONSTANTS 'G3_Yk'              DATA         100.000      ; halfrate const for TIM of DEB ensis
CONSTANTS 'G3_rMor'            DATA         0.000000E-00 ; reference mortality rate of DEB ensis
CONSTANTS 'G3_cMor'            DATA         0.00000      ; length coefficient harvesting rate DEB ensis
CONSTANTS 'G3_rHrv'            DATA         0.00000      ; reference rate of harvesting of DEB ensis
CONSTANTS 'G3_cHrv'            DATA         0.00000      ; length coefficient harvesting rate DEB ensis
CONSTANTS 'G3_cEC'             DATA         0.355555E-04 ; energy to carbon conversion of DEB ensis
CONSTANTS 'G3_cVC'             DATA         0.480000E-01 ; volume to carbon conversion of DEB ensis
CONSTANTS 'G3_cAFWC'           DATA         0.400000     ; AFD weight to carbon conv of DEB ensis
;CONSTANTS 'G3_cWWC'            DATA         0.224000E-01 ; wetweight to carbon conv of DEB ensis
CONSTANTS 'G3_TC'              DATA         1.00000e+000 ; C:C ratio of DEB ensis
CONSTANTS 'G3_TN'              DATA         0.181800     ; N:C ratio of DEB ensis
CONSTANTS 'G3_TP'              DATA         0.263000E-01 ; P:C ratio of DEB ensis
CONSTANTS 'G3_TSi'             DATA         0.00000      ; Si:C ratio of DEB ensis
CONSTANTS 'G3_FrDetS1'         DATA         1.00000e+000 ; fraction of DEB ensis detritus into sediment
CONSTANTS 'G3_SWBen'           DATA         1.00000e+000 ; SWBen specifies the location of the grazers, pelagic = 0, benthic = 1, suspended = 2
CONSTANTS 'G3_SFSusp'          DATA         1.00000e+000 ; DEB ensis pref suspension over deposit feeding
CONSTANTS 'G3_PrDet'           DATA         0.00000      ; DEB ensis preference for DetC or POC1
CONSTANTS 'G3_PrDetS1'         DATA         0.00000      ; DEB ensis preference for DetCS1
CONSTANTS 'G3_FFDet'           DATA         0.500000     ; Faecal fraction of DetC for DEB ensis
CONSTANTS 'G3_FFDetS1'         DATA         0.500000     ; Faecal fraction of DetCS1 for DEB ensis
CONSTANTS 'G3_PrAlg01'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl E                [-]
CONSTANTS 'G3_PrAlg02'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl N                [-]
CONSTANTS 'G3_PrAlg03'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of DinoFl P                [-]
CONSTANTS 'G3_PrAlg04'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat E                  [-]
CONSTANTS 'G3_PrAlg05'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat-N                  [-]
CONSTANTS 'G3_PrAlg06'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Diat-P                  [-]
CONSTANTS 'G3_PrAlg07'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-E                  [-]
CONSTANTS 'G3_PrAlg08'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-N                  [-]
CONSTANTS 'G3_PrAlg09'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of Flag-P                  [-]
CONSTANTS 'G3_PrAlg10'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-E                 [-]
CONSTANTS 'G3_PrAlg11'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-N                 [-]
CONSTANTS 'G3_PrAlg12'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of Phaeo-P                 [-]
CONSTANTS 'G3_PrAlg13'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-E                 [-]
CONSTANTS 'G3_PrAlg14'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-N                 [-]
CONSTANTS 'G3_PrAlg15'     DATA     1.00000E+000 ; MALGPR          Prefernce of grazer of UlvaS-P                 [-]
CONSTANTS 'G3_PrAlg16'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-E                 [-]
CONSTANTS 'G3_PrAlg17'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-N                 [-]
CONSTANTS 'G3_PrAlg18'     DATA     0.00000E+000 ; MALGPR          Prefernce of grazer of UlvaF-P                 [-]
