MASS/M2
 1 ; initial conditions follow
 2 ; all values with default
 35*1.0 ; scale factors
1 ;Continuity
8.5 ; OXY
34 ; Salinity
0.01  ; NH4
0.11 ; NO3
0.01; PO4
0.2; Si
0.04; Opal
0.04 ;POC1
0.004; PON1
0.0004; POP1
0 ;DINOFLAG_E
0 ;DINOFLAG_N
0 ;DINOFLAG_P
0 ;MDIATOMS_E
0 ;MDIATOMS_N
0 ;MDIATOMS_P
0 ;MFLAGELA_E
0 ;MFLAGELA_N
0 ;MFLAGELA_P
0 ;PHAEOCYS_E
0 ;PHAEOCYS_N
0 ;PHAEOCYS_P
0 ;DetCS1
0 ;DetNS1
0 ;DetPS1
0 ;DetSiS1
0 ; MALS
0 ; MALN
0 ; MALP
0 ; MALC
0 ; Mussel_V
0 ; Mussel_E
0 ; Mussel_R
0 ; Mussel_N

2  ; number of overridings

9845; first overriding
1 ;Continuity
8.5 ; OXY
34 ; Salinity
0.01  ; NH4
0.11 ; NO3
0.01; PO4
0.2; Si
0.04; Opal
0.04 ;POC1
0.004; PON1
0.0004; POP1
0 ;DINOFLAG_E
0 ;DINOFLAG_N
0 ;DINOFLAG_P
0 ;MDIATOMS_E
0 ;MDIATOMS_N
0 ;MDIATOMS_P
0 ;MFLAGELA_E
0 ;MFLAGELA_N
0 ;MFLAGELA_P
0 ;PHAEOCYS_E
0 ;PHAEOCYS_N
0 ;PHAEOCYS_P
0 ;DetCS1
0 ;DetNS1
0 ;DetPS1
0 ;DetSiS1

1.24E+01; MALS
1.24E-01; MALN
1.24E-02; MALP
7.45E+00; MALC

0 ; Mussel_V
0 ; Mussel_E
0       ; Mussel_R
0       ; Mussel_N
 
3881 ; second overriding
1 ;Continuity
8.5 ; OXY
34 ; Salinity
0.01  ; NH4
0.11 ; NO3
0.01; PO4
0.2; Si
0.04; Opal
0.04 ;POC1
0.004; PON1
0.0004; POP1
0 ;DINOFLAG_E
0 ;DINOFLAG_N
0 ;DINOFLAG_P
0 ;MDIATOMS_E
0 ;MDIATOMS_N
0 ;MDIATOMS_P
0 ;MFLAGELA_E
0 ;MFLAGELA_N
0 ;MFLAGELA_P
0 ;PHAEOCYS_E
0 ;PHAEOCYS_N
0 ;PHAEOCYS_P
0 ;DetCS1
0 ;DetNS1
0 ;DetPS1
0 ;DetSiS1
0.0  ;MALS
0.0  ;MALN
0.0  ;MALP
0.0  ;MALC
3.06e-8 ; Mussel_V
3.06e-9 ; Mussel_E
0       ; Mussel_R
1       ; Mussel_N
